const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root='.runtime/sources';const rows=JSON.parse(fs.readFileSync(root+'/index.json','utf8'));
const patterns={tractores:/tractor|\b6615\b|\b6415\b|puma/ig,cosecha:/cosech|640fd|745fd|plataforma/ig,filtros:/filtro|filter/ig,lubricacion:/lubrica|aceite|oil|grasa/ig,hidraulica:/hidr[aá]ul|hydraulic/ig,electrico:/el[eé]ctric|voltaje|sensor/ig,herramientas:/herramient|calibraci[oó]n/ig,comercial:/factura|remito|cotizaci[oó]n|precio|subtotal/ig,mantenimiento:/mantenim|maintenance|intervalo|service/ig};
const totals={references:rows.length,textRead:0,textMissing:0,characters:0,originalMissing:0,originalChanged:0};const topics={};const results=[];
for(const row of rows){const file=row.textFile?path.resolve(root,row.textFile):null;let text='';if(file&&file.startsWith(path.resolve(root)+path.sep)&&fs.existsSync(file)){text=fs.readFileSync(file,'utf8');totals.textRead++;totals.characters+=text.length;}else totals.textMissing++;
let integrity='MISSING';if(fs.existsSync(row.path)){const hash=crypto.createHash('sha256').update(fs.readFileSync(row.path)).digest('hex');integrity=hash===row.sha256?'MATCH':'CHANGED';if(integrity==='CHANGED')totals.originalChanged++;}else totals.originalMissing++;
const matched=[];for(const [topic,re] of Object.entries(patterns)){re.lastIndex=0;if(re.test(text)){matched.push(topic);topics[topic]=(topics[topic]||0)+1;}}
results.push({id:row.id,name:row.name,kind:row.kind,status:row.extractionStatus,integrity,characters:text.length,topics:matched,review:'A_CONFIRMAR'});}
fs.mkdirSync('.runtime/corpus-analysis',{recursive:true});fs.writeFileSync('.runtime/corpus-analysis/analysis.json',JSON.stringify({date:new Date().toISOString(),totals,topics,results},null,2));
fs.writeFileSync('docs/CORPUS-ANALYSIS.md',`# Análisis del corpus técnico — 2026-09-15\n\nMétodo: lectura automatizada de todos los textos asociados al índice, búsqueda temática y SHA-256 de originales accesibles. No es lectura semántica humana de todos los manuales ni OCR nuevo. No se modifican originales ni se cargan candidatos reales.\n\n## Cobertura comprobada\n\n${Object.entries(totals).map(([k,v])=>'- '+k+': '+v).join('\n')}\n\n## Temas presentes en texto\n\nUn documento puede aparecer en varios grupos. Coincidencia léxica, no clasificación técnica validada.\n\n${Object.entries(topics).map(([k,v])=>'- '+k+': '+v+' fuentes').join('\n')}\n\n## Interpretación\n\nEl corpus mezcla evidencia técnica, material de taller e historial comercial. Los textos sirven para localizar fuentes por equipo/componente, pero no demuestran aplicabilidad OEM ni stock. Los cambios de hash exigen nueva revisión; ausencia de texto exige lectura visual/OCR. Revisar primero fuentes de la unidad elegida y preservar página, serie, variante y sustituciones. ECT-HER requiere separar taxonomía interna de conformidad normativa. Facturas se analizan como historial, con moneda/fecha/cantidad literales.\n\nEl detalle por referencia queda en .runtime/corpus-analysis/analysis.json (local, fuera de Git). Las salidas anteriores de normalización no se sobrescribieron. Próximo paso: elegir un lote acotado, revisar originales y registrar sus candidatos mediante el flujo persistente; no importar todo automáticamente.\n`);
console.log(JSON.stringify({totals,topics}));
